version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: MongoDB
    ports:
      - '27017:27017'
    volumes:
      - db_mongo:/data/db
  
  api:
    image: t2_back
    container_name: api_container
    ports:
      - '4000:4000'
    restart: always
    depends_on:
      - mongodb
  
  front:
    image: t2_front
    container_name: front_container
    ports:
      - '3000:3000'
    restart: always
    depends_on:
      - api
    #links:
    #  - api
volumes:
  db_mongo: