// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GreetMemoriaLibre():Promise<number>;

export function GreetMemoriaUsada():Promise<number>;
