// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GreetMemoriaLibre() {
  return window['go']['main']['App']['GreetMemoriaLibre']();
}

export function GreetMemoriaUsada() {
  return window['go']['main']['App']['GreetMemoriaUsada']();
}
